name: mineunit

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - id: mineunit
      uses: mt-mods/mineunit-actions@master
      with:
        working-directory: .
